import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen flex flex-col max-w-3xl mx-auto px-4">
          {/* Header appears on ALL pages */}
          {/* Main content area */}
          <main className="flex-grow">{children}</main>
          {/* Footer appears on ALL pages */}
        </div>
      </body>
    </html>
  );
}
